neo_font.settings:
  type: config_object
  mapping:
    primary:
      type: string
      label: Primary
    secondary:
      type: string
      label: Secondary
    accent:
      type: string
      label: Accent
    heading:
      type: string
      label: Heading
    ui:
      type: string
      label: User Interface
